In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
date_index = pd.date_range('20200101',periods=4)#Same datetime format, periods means how many
date_index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04'], dtype='datetime64[ns]', freq='D')

In [6]:
np_array = np.random.randint(100,size=(4,4))# Multi dimentional array size means rows and columns
np_array

array([[57, 98, 47, 72],
       [46, 83, 62, 80],
       [48, 88, 45,  9],
       [58, 36, 76, 97]])

In [7]:
#Now creating Dataframe
my_df = pd.DataFrame(np_array,index=date_index,columns=list('ABCD'))
# Dataframe means rows and columns
# By default index will be rows and columns will be none
my_df

A   B   C   D
2020-01-01  57  98  47  72
2020-01-02  46  83  62  80
2020-01-03  48  88  45   9
2020-01-04  58  36  76  97

In [14]:
### Handling dictionaries
my_df1 = pd.DataFrame({
    "name":list("ABCDEFGH"), #key==column name and values are rows-------------------
    "age": np.random.randint(10,size=8),
    "date":pd.Timestamp('20201109'),
    "ranking":np.array([5]*8),
    "Faul":"Foo",
    "number":9
    
})

In [15]:
my_df1

name  age       date  ranking Faul  number
0    A    1 2020-11-09        5  Foo       9
1    B    5 2020-11-09        5  Foo       9
2    C    8 2020-11-09        5  Foo       9
3    D    9 2020-11-09        5  Foo       9
4    E    5 2020-11-09        5  Foo       9
5    F    8 2020-11-09        5  Foo       9
6    G    5 2020-11-09        5  Foo       9
7    H    4 2020-11-09        5  Foo       9

In [10]:
my_df1.dtypes

name               object
age                 int64
date       datetime64[ns]
ranking             int64
Faul               object
dtype: object

In [16]:
my_df1.head(3)

name  age       date  ranking Faul  number
0    A    1 2020-11-09        5  Foo       9
1    B    5 2020-11-09        5  Foo       9
2    C    8 2020-11-09        5  Foo       9

In [17]:
my_df.tail(4)

A   B   C   D
2020-01-01  57  98  47  72
2020-01-02  46  83  62  80
2020-01-03  48  88  45   9
2020-01-04  58  36  76  97

In [22]:
my_df.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04'], dtype='datetime64[ns]', freq='D')

In [23]:
my_df1.index

RangeIndex(start=0, stop=8, step=1)

In [24]:
# Dataframe to numpy conversion
# Can be very expensive due to dtype as numpy can have one datatype
# So data frame with columns of different datatypes can create a real mess
my_df1.to_numpy()

array([['A', 1, Timestamp('2020-11-09 00:00:00'), 5, 'Foo', 9],
       ['B', 5, Timestamp('2020-11-09 00:00:00'), 5, 'Foo', 9],
       ['C', 8, Timestamp('2020-11-09 00:00:00'), 5, 'Foo', 9],
       ['D', 9, Timestamp('2020-11-09 00:00:00'), 5, 'Foo', 9],
       ['E', 5, Timestamp('2020-11-09 00:00:00'), 5, 'Foo', 9],
       ['F', 8, Timestamp('2020-11-09 00:00:00'), 5, 'Foo', 9],
       ['G', 5, Timestamp('2020-11-09 00:00:00'), 5, 'Foo', 9],
       ['H', 4, Timestamp('2020-11-09 00:00:00'), 5, 'Foo', 9]],
      dtype=object)

In [25]:
#Numpy array does not include column names
my_df.to_numpy()

array([[57, 98, 47, 72],
       [46, 83, 62, 80],
       [48, 88, 45,  9],
       [58, 36, 76, 97]])

In [26]:
np.array([1,2.0,'l'])# can have one kind of datatypes here converted every thing to string

array(['1', '2.0', 'l'], dtype='<U32')

In [27]:
np.array([1,2.2,3,4])# here converted everything to float

array([1. , 2.2, 3. , 4. ])

In [33]:
## so its better to convert Series or columns
a=my_df['A'].to_numpy()
a


array([57, 46, 48, 58])

In [35]:
my_df

A   B   C   D
2020-01-01  57  98  47  72
2020-01-02  46  83  62  80
2020-01-03  48  88  45   9
2020-01-04  58  36  76  97

In [34]:
my_df.describe()

A          B          C         D
count   4.000000   4.000000   4.000000   4.00000
mean   52.250000  76.250000  57.500000  64.50000
std     6.130525  27.548442  14.479871  38.44043
min    46.000000  36.000000  45.000000   9.00000
25%    47.500000  71.250000  46.500000  56.25000
50%    52.500000  85.500000  54.500000  76.00000
75%    57.250000  90.500000  65.500000  84.25000
max    58.000000  98.000000  76.000000  97.00000

In [36]:
my_df.T  ###Transpose matrix----- rows==columns &&& columns===rows

2020-01-01  2020-01-02  2020-01-03  2020-01-04
A          57          46          48          58
B          98          83          88          36
C          47          62          45          76
D          72          80           9          97

In [38]:
my_df

A   B   C   D
2020-01-01  57  98  47  72
2020-01-02  46  83  62  80
2020-01-03  48  88  45   9
2020-01-04  58  36  76  97

In [39]:
my_df.sort_values('B') ###  Sorting values by columns default=acsending

A   B   C   D
2020-01-04  58  36  76  97
2020-01-02  46  83  62  80
2020-01-03  48  88  45   9
2020-01-01  57  98  47  72

In [40]:
new_df=my_df.sort_values('B')

In [43]:
new_df.sort_index(ascending=False)

A   B   C   D
2020-01-04  58  36  76  97
2020-01-03  48  88  45   9
2020-01-02  46  83  62  80
2020-01-01  57  98  47  72

In [44]:
new_df.sort_index(ascending=1)

A   B   C   D
2020-01-01  57  98  47  72
2020-01-02  46  83  62  80
2020-01-03  48  88  45   9
2020-01-04  58  36  76  97

In [45]:
my_df1

name  age       date  ranking Faul  number
0    A    1 2020-11-09        5  Foo       9
1    B    5 2020-11-09        5  Foo       9
2    C    8 2020-11-09        5  Foo       9
3    D    9 2020-11-09        5  Foo       9
4    E    5 2020-11-09        5  Foo       9
5    F    8 2020-11-09        5  Foo       9
6    G    5 2020-11-09        5  Foo       9
7    H    4 2020-11-09        5  Foo       9

In [46]:
my_df1[:5]

name  age       date  ranking Faul  number
0    A    1 2020-11-09        5  Foo       9
1    B    5 2020-11-09        5  Foo       9
2    C    8 2020-11-09        5  Foo       9
3    D    9 2020-11-09        5  Foo       9
4    E    5 2020-11-09        5  Foo       9

In [48]:
my_df1['date'] # taking columns as Series objects Remeber dictionary keys as columnns and rows as values

0   2020-11-09
1   2020-11-09
2   2020-11-09
3   2020-11-09
4   2020-11-09
5   2020-11-09
6   2020-11-09
7   2020-11-09
Name: date, dtype: datetime64[ns]

In [50]:
my_df1.loc[0] ## searching by rows

name                         A
age                          1
date       2020-11-09 00:00:00
ranking                      5
Faul                       Foo
number                       9
Name: 0, dtype: object

In [53]:
my_df.loc['2020-01-01']### indexed by datetime object

A    57
B    98
C    47
D    72
Name: 2020-01-01 00:00:00, dtype: int64

In [54]:
my_df

A   B   C   D
2020-01-01  57  98  47  72
2020-01-02  46  83  62  80
2020-01-03  48  88  45   9
2020-01-04  58  36  76  97

In [55]:
my_df.loc[:,['A','C']] ## All rows and selected columns

A   C
2020-01-01  57  47
2020-01-02  46  62
2020-01-03  48  45
2020-01-04  58  76

In [58]:
my_df.loc[date_index[0]] ##Selecting by labels

A    57
B    98
C    47
D    72
Name: 2020-01-01 00:00:00, dtype: int64

In [59]:
my_df

A   B   C   D
2020-01-01  57  98  47  72
2020-01-02  46  83  62  80
2020-01-03  48  88  45   9
2020-01-04  58  36  76  97

In [62]:
## Selecting by position here loc won't work
my_df.iloc[0]

A    57
B    98
C    47
D    72
Name: 2020-01-01 00:00:00, dtype: int64

In [65]:
my_df.iloc[:3,:3] ### rows and columns

A   B   C
2020-01-01  57  98  47
2020-01-02  46  83  62
2020-01-03  48  88  45

In [66]:
my_df.iloc[[1,2,3],[0,2]]

A   C
2020-01-02  46  62
2020-01-03  48  45
2020-01-04  58  76

In [67]:
my_df.iat[1,1]## to check a scalar

83

In [68]:
my_df

A   B   C   D
2020-01-01  57  98  47  72
2020-01-02  46  83  62  80
2020-01-03  48  88  45   9
2020-01-04  58  36  76  97

In [71]:
## Boolean indexing
my_df['A']>48

2020-01-01     True
2020-01-02    False
2020-01-03    False
2020-01-04     True
Freq: D, Name: A, dtype: bool

In [72]:
my_df[my_df['A']>48] ### To get the dataframe

A   B   C   D
2020-01-01  57  98  47  72
2020-01-04  58  36  76  97

In [73]:
my_df[my_df>48] ### will show dataframe with values greater than 48 and rest as NaN

A     B     C     D
2020-01-01  57.0  98.0   NaN  72.0
2020-01-02   NaN  83.0  62.0  80.0
2020-01-03   NaN  88.0   NaN   NaN
2020-01-04  58.0   NaN  76.0  97.0

In [75]:
df =my_df.copy()

In [76]:
df['E']=['yes','no','yes','yes'] ## Adding a column like dictionary

In [78]:
df[df['E']=='yes']

A   B   C   D    E
2020-01-01  57  98  47  72  yes
2020-01-03  48  88  45   9  yes
2020-01-04  58  36  76  97  yes

In [79]:
ndf = my_df[my_df>48]
ndf

A     B     C     D
2020-01-01  57.0  98.0   NaN  72.0
2020-01-02   NaN  83.0  62.0  80.0
2020-01-03   NaN  88.0   NaN   NaN
2020-01-04  58.0   NaN  76.0  97.0

In [80]:
ndf.fillna(4.7) ### Filling up missing values

A     B     C     D
2020-01-01  57.0  98.0   4.7  72.0
2020-01-02   4.7  83.0  62.0  80.0
2020-01-03   4.7  88.0   4.7   4.7
2020-01-04  58.0   4.7  76.0  97.0

In [81]:
ndf.mean() #Based on columns

A    57.500000
B    89.666667
C    69.000000
D    83.000000
dtype: float64

In [82]:
## Same operations in other axis
ndf.mean(1) # Based on rows

2020-01-01    75.666667
2020-01-02    75.000000
2020-01-03    88.000000
2020-01-04    77.000000
Freq: D, dtype: float64

In [89]:
df3=df[['A','B']]
df3

A   B
2020-01-01  57  98
2020-01-02  46  83
2020-01-03  48  88
2020-01-04  58  36

In [88]:
df3.apply(lambda x: x.max() - x.min()) # lambda function working on columns

A    12
B    62
dtype: int64

In [92]:
#### frequency counts 
df['E'].value_counts()

yes    3
no     1
Name: E, dtype: int64

In [94]:
df['E'].str.upper() ##### Applying string methods

2020-01-01    YES
2020-01-02     NO
2020-01-03    YES
2020-01-04    YES
Freq: D, Name: E, dtype: object

In [96]:
dfa=pd.DataFrame(np.random.randint(40,size=(4,4)))
dfb=pd.DataFrame(np.random.randint(40,100,size=(4,4)))


In [97]:
dfa

0   1   2   3
0  11  17   3  24
1   3  39   0   3
2  18   5  37  34
3  19  17  37  16

In [98]:
dfb

0   1   2   3
0  69  57  79  86
1  68  82  46  57
2  98  93  40  74
3  65  45  58  62

In [101]:
pd.concat([dfa,dfb]) ## Merging adding rows

0   1   2   3
0  11  17   3  24
1   3  39   0   3
2  18   5  37  34
3  19  17  37  16
0  69  57  79  86
1  68  82  46  57
2  98  93  40  74
3  65  45  58  62

In [107]:
### Sql style merging
dfa=pd.DataFrame({
    'name':list('ABCD'),
    'age':np.random.randint(20,size=4)      
})
dfb=pd.DataFrame({
    'name':list('ABCD'),
    'salary':np.random.randint(200,400,size=4)      
})
dfa

name  age
0    A    5
1    B   19
2    C   14
3    D   17

In [108]:
dfb

name  salary
0    A     300
1    B     267
2    C     243
3    D     207

In [109]:
pd.merge(dfa,dfb,on="name") ### just like foreign key

name  age  salary
0    A    5     300
1    B   19     267
2    C   14     243
3    D   17     207

In [121]:
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
                   'B': ['one', 'one', 'two', 'three','two', 'two', 'one', 'three'],
                   'C': np.random.randn(8),
                   'D': np.random.randn(8)})

df

A      B         C         D
0  foo    one -0.226156  0.087875
1  bar    one  0.654532  0.027314
2  foo    two  0.619462 -1.706407
3  bar  three  3.086097 -1.651887
4  foo    two  0.143446 -1.102506
5  bar    two -1.004841 -2.594884
6  foo    one -1.607101 -1.367509
7  foo  three -0.765492  0.466939

In [115]:
## Group by ----- grouping by one criteria+ applying fuction + return dataframe
df.groupby('A').sum()

C         D
A                      
bar  0.967325 -1.232785
foo -3.180690  1.842180

In [116]:
df.groupby(['A','B']).sum() # First grouped 'A' then 'B', then function

C         D
A   B                        
bar one    0.525474  0.217714
    three -0.419586 -0.868697
    two    0.861437 -0.581802
foo one    0.867274  1.881195
    three -1.950715  0.715073
    two   -2.097249 -0.754087

In [118]:
rng = pd.date_range('1/1/2012', periods=5, freq='M')
rng

DatetimeIndex(['2012-01-31', '2012-02-29', '2012-03-31', '2012-04-30',
               '2012-05-31'],
              dtype='datetime64[ns]', freq='M')

In [120]:
rng = pd.date_range('1/1/2012', periods=5, freq='S')
rng

DatetimeIndex(['2012-01-01 00:00:00', '2012-01-01 00:00:01',
               '2012-01-01 00:00:02', '2012-01-01 00:00:03',
               '2012-01-01 00:00:04'],
              dtype='datetime64[ns]', freq='S')

In [123]:
def color_negative_red(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
    color = 'red' if val < 0 else 'black'
    return 'color: %s' % color

In [125]:
s = df[['C','D']].style.applymap(color_negative_red) ### Styling
s

In [126]:
df

A      B         C         D
0  foo    one -0.226156  0.087875
1  bar    one  0.654532  0.027314
2  foo    two  0.619462 -1.706407
3  bar  three  3.086097 -1.651887
4  foo    two  0.143446 -1.102506
5  bar    two -1.004841 -2.594884
6  foo    one -1.607101 -1.367509
7  foo  three -0.765492  0.466939

In [ ]:
 ts = pd.Series(np.random.randn(1000),
                index=pd.date_range('1/1/2000', periods=1000)) 

In [4]: ts = ts.cumsum()

In [5]: ts.plot()